input_basedir: "."

input:
#
#
  - name: "patterns"

output_basedir: "../svg_patterns"
# WARNING: deletes all files within output directory if it exists
empty_output: true
format: "svg"

global_style:
  fill: "#734a08"

power-wind:
  fill: "#555555"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
hunting-stand:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
viewpoint:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
cliff:
  fill: "#555555"
rock:
  fill: "#555555"
cave-entrance:
  fill: "#000000"
peak:
  fill: "#999999"
  halo:
    fill: "#000000"
    width: 1
    opacity: 1.0
vulcan:
  fill: "#990000"
  halo:
    fill: "#000000"
    width: 1
    opacity: 1.0
stone:
  fill: "#555555"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
saddle:
  fill: "#d08f55"
rental-bicycle:
  fill: "#0092da"
airport:
  fill: "#0092da"
heliport:
  fill: "#0092da"
metro:
  fill: "#0092da"
railway-halt:
  fill: "#0092da"
railway-station:
  fill: "#0092da"
taxi:
  fill: "#0092da"
tram-stop:
  fill: "#0092da"
board:
  fill: "#ffffff"
  shield:
    fill: "#55aa55"
    stroke_fill: "#1a1a1a"
    stroke_width: 1
    rounded: 3
    padding: 2
map:
  fill: "#ffffff"
  shield:
    fill: "#55aa55"
    stroke_fill: "#1a1a1a"
    stroke_width: 1
    rounded: 3
    padding: 2
information-office:
  fill: "#ffffff"
  shield:
    fill: "#55aa55"
    stroke_fill: "#1a1a1a"
    stroke_width: 1
    rounded: 3
    padding: 2
bus-stop:
  fill: "#0092da"
bus-station:
  fill: "#0092da"
  shield:
    fill: "#ffffff"
    opacity: 0.5
    stroke_fill: "#0092da"
    stroke_width: 2
    rounded: 10
    padding: 4
lighthouse:
  fill: "#0092da"
camping:
  fill: "#0092da"
caravan:
  fill: "#0092da"
shared-car:
  fill: "#0092da"
rental-car:
  fill: "#0092da"
elevator:
  fill: "#0092da"
fuel:
  fill: "#0092da"
ferry:
  fill: "#0092da"
charging-station:
  fill: "#0092da"
subway-entrance:
  fill: "#0092da"
ford:
  fill: "#0092da"
hostel:
  fill: "#0092da"
hotel:
  fill: "#0092da"
motel:
  fill: "#0092da"
embassy:
  fill: "#0092da"
parking-car:
  fill: "#0092da"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
parking-bicycle:
  fill: "#0092da"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
parking-garage-car:
  fill: "#0092da"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
lift-gate:
  fill: "#ff0000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
picnic-site:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
hospital:
  fill: "#da0000"
mountain-rescue:
  fill: "#da0000"
doctor:
  fill: "#da0092"
pharmacy:
  fill: "#da0092"
dentist:
  fill: "#da0092"
mast:
  fill: "#555555"
mast-communications:
  fill: "#555555"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
water-tower:
  fill: "#555555"
spring:
  fill: "#2d2dec"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
christian:
  fill: "#000000"
christian-orthodox:
  fill: "#000000"
place-of-worship:
  fill: "#000000"
taoist:
  fill: "#000000"
buddhist:
  fill: "#000000"
hinduist:
  fill: "#000000"
sikhist:
  fill: "#000000"
muslim:
  fill: "#000000"
jewish:
  fill: "#000000"
shintoist:
  fill: "#000000"
alcohol:
  fill: "#ac39ac"
bakery:
  fill: "#ac39ac"
bicycle:
  fill: "#ac39ac"
no-bicycle:
  fill: "#000000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#ff0000"
    stroke_width: 2
    rounded: 10
    padding: 2
traffic-signal:
  fill: "#000000"
books:
  fill: "#ac39ac"
butcher:
  fill: "#ac39ac"
car:
  fill: "#ac39ac"
clothes:
  fill: "#ac39ac"
convenience:
  fill: "#ac39ac"
doityourself:
  fill: "#ac39ac"
electronics:
  fill: "#ac39ac"
florist:
  fill: "#ac39ac"
furniture:
  fill: "#ac39ac"
gift:
  fill: "#ac39ac"
greengrocer:
  fill: "#ac39ac"
hairdresser:
  fill: "#ac39ac"
jewellery:
  fill: "#ac39ac"
kiosk:
  fill: "#ac39ac"
ice-cream:
  fill: "#ac39ac"
mobile-phone:
  fill: "#ac39ac"
optician:
  fill: "#ac39ac"
pet:
  fill: "#ac39ac"
shoes:
  fill: "#ac39ac"
supermarket:
  fill: "#ac39ac"
confectionery:
  fill: "#ac39ac"
computer:
  fill: "#ac39ac"
photo:
  fill: "#ac39ac"
car-parts:
  fill: "#ac39ac"
beauty:
  fill: "#ac39ac"
news:
  fill: "#ac39ac"
hifi:
  fill: "#ac39ac"
laundry:
  fill: "#ac39ac"
beverages:
  fill: "#ac39ac"
stationery:
  fill: "#ac39ac"
toys:
  fill: "#ac39ac"
garden-centre:
  fill: "#ac39ac"
copyshop:
  fill: "#ac39ac"
chemist:
  fill: "#ac39ac"
repair-car:
  fill: "#ac39ac"
repair-bicycle:
  fill: "#ac39ac"
veterinary:
  fill: "#da0092"
guidepost:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
bench:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
memorial:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
oneway:
  fill: "#555555"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
oneway-closedway:
  fill: "#555555"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
opposite-lane:
  fill: "#555555"
  halo:
    fill: "#ff55ff"
    width: 1
    opacity: 1.0
opposite-lane-reversed:
  fill: "#555555"
  halo:
    fill: "#ff55ff"
    width: 1
    opacity: 1.0
cliff-line:
  fill: "#555555"
cliff-line-closedway:
  fill: "#555555"
railway-crossing:
  fill: "#ffffff"
  halo:
    fill: "#ff0000"
    width: 1
    opacity: 1.0
railway-crossing-small:
  fill: "#ffffff"
  halo:
    fill: "#ff0000"
    width: 1
    opacity: 1.0
pillbox:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 0.2
    opacity: 1.0
tree-point:
  fill: "#4fc60f"
ruin:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
castle-ruin:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
castle-fortress:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
cable-car:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
chair-lift:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
gondola:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
fire-station:
  fill: "#ff0000"
  halo:
    fill: "#ffa500"
    width: 1
    opacity: 1.0
shelter:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
church:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
swimming:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
soccer:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
tennis:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
continue:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
noexit:
  fill: "#ffffff"
  halo:
    fill: "#ff0000"
    width: 0.5
  shield:
    fill: "#2d2dec"
    stroke_fill: "#1a1a1a"
    stroke_width: 0.5
    rounded: 3
    opacity: 0.5
sac-ti:
  fill: "#000000"
  shield:
    fill: "#ffe700"
    stroke_fill: "#000000"
    stroke_width: 0.1
    rounded: 3
    opacity: 0.3
sac-tii:
  fill: "#000000"
  shield:
    fill: "#fd817a"
    stroke_fill: "#000000"
    stroke_width: 0.1
    rounded: 3
    opacity: 0.3
sac-tiii:
  fill: "#000000"
  shield:
    fill: "#ff0e00"
    stroke_fill: "#000000"
    stroke_width: 0.1
    rounded: 3
    opacity: 0.3
sac-tiv:
  fill: "#000000"
  shield:
    fill: "#80a7f9"
    stroke_fill: "#000000"
    stroke_width: 0.1
    rounded: 3
    opacity: 0.3
sac-tv:
  fill: "#000000"
  shield:
    fill: "#427af2"
    stroke_fill: "#000000"
    stroke_width: 0.1
    rounded: 3
    opacity: 0.3
sac-tvi:
  fill: "#000000"
  shield:
    fill: "#0051ff"
    stroke_fill: "#000000"
    stroke_width: 0.1
    rounded: 3
    opacity: 0.3
emergency-phone:
  fill: "#ff0000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
bad-surface:
  fill: "#ffdb00"
  opacity: 0.25
  shield:
    fill: "#000000"
    opacity: 0.25
warning:
  fill: "#ffdb00"
  halo:
    fill: "#000000"
    width: 1
    opacity: 0.5
danger:
  fill: "#ff2b00"
  halo:
    fill: "#ffdb00"
    width: 1
    opacity: 1.0
trail-visibility-good:
  fill: "#774422"
  opacity: 0.9
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 0.6
trail-visibility-bad:
  fill: "#774422"
  opacity: 0.6
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 0.6
trail-visibility-no:
  fill: "#774422"
  opacity: 0.3
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 0.6
#patterns
access-destination:
  fill: "#0000ff"
access-no-bike:
  fill: "#ff00ff"
access-no-foot:
  fill: "#ffaa00"
access-private:
  fill: "#ff0000"
bare-rock:
  fill: "#25281e"
  opacity: 0.5
  shield:
    fill: "#c2b48c"
    opacity: 0.5
cemetery:
  fill: "#999999"
  shield:
    fill: "#bde3cb"
cemetery-christian:
  fill: "#999999"
  shield:
    fill: "#bde3cb"
cemetery-jewish:
  fill: "#999999"
  shield:
    fill: "#bde3cb"
marsh:
  fill: "#0092da"
military:
  fill: "#555555"
  opacity: 0.25
  shield:
    fill: "#ffe649"
    opacity: 0.25
    padding: 2
nature-reserve:
  fill: "#99ff99"
  opacity: 0.5
national-park:
  fill: "#ff9999"
  opacity: 0.2
orchard:
  fill: "#000000"
  shield:
    fill: "#aadca2"
photovoltaic:
  fill: "#ffffff"
  shield:
    fill: "#2222a2"
    opacity: 0.25
plant-nursery:
  fill: "#000000"
  shield:
    fill: "#aadca2"
scree:
  fill: "#35281e"
  opacity: 0.5
  shield:
    fill: "#d2b48c"
    opacity: 0.5
scrub:
  fill: "#569953"
  shield:
    fill: "#96c993"
vineyard:
  fill: "#000000"
  shield:
    fill: "#aadca2"
wood-coniferous:
  fill: "#96b983"
  shield:
    fill: "#a6c993"
wood-deciduous:
  fill: "#96b983"
  shield:
    fill: "#a6c993"
wood-mixed:
  fill: "#96b983"
  shield:
    fill: "#a6c993"
