input_basedir: "."

input:
  - name: "symbol"
  - name: "osmc-symbol"


output_basedir: "export"
# WARNING: deletes all files within output directory if it exists
empty_output: true
format: "sprite"
retina: true
size_filter: 14

global_style:
  padding: 1
  fill: "#1a1a1a"

sprite:
  cols: 12
  outer_padding: 4
  icon_padding: 4
  filename: "icons"
  
power-wind:
  fill: "#555555"
hunting-stand:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
cliff:
  fill: "#d08f55"
peak:
  fill: "#999999"
  halo:
    fill: "#000000"
    width: 1
    opacity: 1.0
stone:
  fill: "#555555"
saddle:
  fill: "#d08f55"
rental-bicycle:
  fill: "#0092da"
airport:
  fill: "#0092da"
heliport:
  fill: "#0092da"
metro:
  fill: "#0092da"
railway-halt:
  fill: "#0092da"
railway-station:
  fill: "#0092da"
taxi:
  fill: "#0092da"
tram-stop:
  fill: "#0092da"
board:
  fill: "#ffffff"
  shield:
    fill: "#55aa55"
    stroke_fill: "#1a1a1a"
    stroke_width: 1
    rounded: 3
    padding: 2
bus-stop:
  fill: "#0092da"
bus-station:
  fill: "#0092da"
lighthouse:
  fill: "#0092da"
camping:
  fill: "#0092da"
caravan:
  fill: "#0092da"
shared-car:
  fill: "#0092da"
rental-car:
  fill: "#0092da"
elevator:
  fill: "#0092da"
fuel:
  fill: "#0092da"
ferry:
  fill: "#0092da"
charging-station:
  fill: "#0092da"
subway-entrance:
  fill: "#0092da"
ford:
  fill: "#0092da"
hostel:
  fill: "#0092da"
hotel:
  fill: "#0092da"
motel:
  fill: "#0092da"
embassy:
  fill: "#0092da"
parking-car:
  fill: "#0092da"
parking-bicycle:
  fill: "#0092da"
parking-garage-car:
  fill: "#0092da"
picnic-site:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
hospital:
  fill: "#da0000"
doctor:
  fill: "#da0092"
pharmacy:
  fill: "#da0092"
dentist:
  fill: "#da0092"
mast:
  fill: "#555555"
mast-communications:
  fill: "#555555"
water-tower:
  fill: "#555555"
christian:
  fill: "#000000"
christian-orthodox:
  fill: "#000000"
place-of-worship:
  fill: "#000000"
taoist:
  fill: "#000000"
buddhist:
  fill: "#000000"
hinduist:
  fill: "#000000"
sikhist:
  fill: "#000000"
muslim:
  fill: "#000000"
jewish:
  fill: "#000000"
shintoist:
  fill: "#000000"
alcohol:
  fill: "#ac39ac"
bakery:
  fill: "#ac39ac"
bicycle:
  fill: "#ac39ac"
books:
  fill: "#ac39ac"
butcher:
  fill: "#ac39ac"
car:
  fill: "#ac39ac"
clothes:
  fill: "#ac39ac"
convenience:
  fill: "#ac39ac"
doityourself:
  fill: "#ac39ac"
electronics:
  fill: "#ac39ac"
florist:
  fill: "#ac39ac"
furniture:
  fill: "#ac39ac"
gift:
  fill: "#ac39ac"
greengrocer:
  fill: "#ac39ac"
hairdresser:
  fill: "#ac39ac"
jewellery:
  fill: "#ac39ac"
kiosk:
  fill: "#ac39ac"
ice-cream:
  fill: "#ac39ac"
mobile-phone:
  fill: "#ac39ac"
optician:
  fill: "#ac39ac"
pet:
  fill: "#ac39ac"
shoes:
  fill: "#ac39ac"
supermarket:
  fill: "#ac39ac"
confectionery:
  fill: "#ac39ac"
computer:
  fill: "#ac39ac"
photo:
  fill: "#ac39ac"
car-parts:
  fill: "#ac39ac"
beauty:
  fill: "#ac39ac"
news:
  fill: "#ac39ac"
hifi:
  fill: "#ac39ac"
laundry:
  fill: "#ac39ac"
beverages:
  fill: "#ac39ac"
stationery:
  fill: "#ac39ac"
toys:
  fill: "#ac39ac"
garden-centre:
  fill: "#ac39ac"
copyshop:
  fill: "#ac39ac"
chemist:
  fill: "#ac39ac"
repair-car:
  fill: "#ac39ac"
repair-bicycle:
  fill: "#ac39ac"
veterinary:
  fill: "#da0092"
guidepost:
  fill: "#000000"
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
bench:
  halo:
    fill: "#ffffff"
    width: 1
    opacity: 1.0
#osmc-symbol
red-white-red-arch:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-arch:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-arch:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-arch:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-arch:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-arch:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-arch:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-arch:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-arch:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-arch:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-arch:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-arch:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-arch:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-backslash:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-backslash:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-backslash:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-backslash:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-backslash:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-backslash:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-backslash:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-backslash:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-backslash:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-backslash:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-backslash:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-backslash:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-backslash:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-bar:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-bar:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-bar:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-bar:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-bar:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-bar:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-bar:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-bar:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-bar:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-bar:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-bar:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-bar:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-bar:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-bowl:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-bowl:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-bowl:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-bowl:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-bowl:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-bowl:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-bowl:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-bowl:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-bowl:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-bowl:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-bowl:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-bowl:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-bowl:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-corner:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-corner:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-corner:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-corner:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-corner:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-corner:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-corner:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-corner:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-corner:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-corner:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-corner:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-corner:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-corner:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-dot:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-dot:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-dot:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-dot:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-dot:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-dot:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-dot:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-dot:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-dot:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-dot:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-dot:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-dot:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-dot:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-l:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-l:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-l:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-l:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-l:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-l:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-l:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-l:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-l:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-l:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-l:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-l:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-l:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-triangle:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-triangle:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-triangle:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-triangle:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-triangle:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-triangle:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-triangle:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-triangle:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-triangle:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-triangle:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-triangle:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-triangle:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-triangle:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-white-red-turned-t:
  fill: "#ff0000"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-yellow-red-turned-t:
  fill: "#ff0000"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
red-orange-red-turned-t:
  fill: "#ff0000"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-white-yellow-turned-t:
  fill: "#ffdd00"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
yellow-orange-yellow-turned-t:
  fill: "#ffdd00"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-white-blue-turned-t:
  fill: "#1579e0"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-yellow-blue-turned-t:
  fill: "#1579e0"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
blue-orange-blue-turned-t:
  fill: "#1579e0"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-white-green-turned-t:
  fill: "#00cd27"
  shield:
    fill: "#ffffff"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-yellow-green-turned-t:
  fill: "#00cd27"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
green-orange-green-turned-t:
  fill: "#00cd27"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-yellow-white-turned-t:
  fill: "#ffffff"
  shield:
    fill: "#ffdd00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
white-orange-white-turned-t:
  fill: "#ffffff"
  shield:
    fill: "#f96f00"
    stroke_fill: "#000000"
    stroke_width: 1    
    padding: 1
