		<osm-tag key="osmc_background" value="black" renderable="false" />
		<osm-tag key="osmc_background" value="black_circle" renderable="false" />
		<osm-tag key="osmc_background" value="black_frame" renderable="false" />
		<osm-tag key="osmc_background" value="black_round" renderable="false" />
		<osm-tag key="osmc_background" value="blue" renderable="false" />
		<osm-tag key="osmc_background" value="blue_circle" renderable="false" />
		<osm-tag key="osmc_background" value="blue_frame" renderable="false" />
		<osm-tag key="osmc_background" value="blue_round" renderable="false" />
		<osm-tag key="osmc_background" value="brown" renderable="false" />
		<osm-tag key="osmc_background" value="brown_circle" renderable="false" />
		<osm-tag key="osmc_background" value="brown_frame" renderable="false" />
		<osm-tag key="osmc_background" value="brown_round" renderable="false" />
		<osm-tag key="osmc_background" value="gray" renderable="false" />
		<osm-tag key="osmc_background" value="gray_circle" renderable="false" />
		<osm-tag key="osmc_background" value="gray_frame" renderable="false" />
		<osm-tag key="osmc_background" value="gray_round" renderable="false" />
		<osm-tag key="osmc_background" value="green" renderable="false" />
		<osm-tag key="osmc_background" value="green_circle" renderable="false" />
		<osm-tag key="osmc_background" value="green_frame" renderable="false" />
		<osm-tag key="osmc_background" value="green_round" renderable="false" />
		<osm-tag key="osmc_background" value="none" renderable="false" />
		<osm-tag key="osmc_background" value="orange" renderable="false" />
		<osm-tag key="osmc_background" value="orange_circle" renderable="false" />
		<osm-tag key="osmc_background" value="orange_frame" renderable="false" />
		<osm-tag key="osmc_background" value="orange_round" renderable="false" />
		<osm-tag key="osmc_background" value="purple" renderable="false" />
		<osm-tag key="osmc_background" value="purple_circle" renderable="false" />
		<osm-tag key="osmc_background" value="purple_frame" renderable="false" />
		<osm-tag key="osmc_background" value="purple_round" renderable="false" />
		<osm-tag key="osmc_background" value="red" renderable="false" />
		<osm-tag key="osmc_background" value="red_circle" renderable="false" />
		<osm-tag key="osmc_background" value="red_frame" renderable="false" />
		<osm-tag key="osmc_background" value="red_round" renderable="false" />
		<osm-tag key="osmc_background" value="white" renderable="false" />
		<osm-tag key="osmc_background" value="white_circle" renderable="false" />
		<osm-tag key="osmc_background" value="white_frame" renderable="false" />
		<osm-tag key="osmc_background" value="white_round" renderable="false" />
		<osm-tag key="osmc_background" value="yellow" renderable="false" />
		<osm-tag key="osmc_background" value="yellow_circle" renderable="false" />
		<osm-tag key="osmc_background" value="yellow_frame" renderable="false" />
		<osm-tag key="osmc_background" value="yellow_round" renderable="false" />
		<osm-tag key="osmc_foreground" value="ammonit" renderable="false" />
		<osm-tag key="osmc_foreground" value="backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_ammonit" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_crest" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_tower" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="heart" renderable="false" />
		<osm-tag key="osmc_foreground" value="hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="L" renderable="false" />
		<osm-tag key="osmc_foreground" value="mine" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_crest" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_tower" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="shell" renderable="false" />
		<osm-tag key="osmc_foreground" value="shell_modern" renderable="false" />
		<osm-tag key="osmc_foreground" value="tower" renderable="false" />
		<osm-tag key="osmc_foreground" value="triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_crest" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_shell" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_shell" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_shell_modern" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_x" renderable="false" />
		<osm-tag key="osmc_background" value="black" renderable="false" />
		<osm-tag key="osmc_background" value="black_circle" renderable="false" />
		<osm-tag key="osmc_background" value="black_frame" renderable="false" />
		<osm-tag key="osmc_background" value="black_round" renderable="false" />
		<osm-tag key="osmc_background" value="blue" renderable="false" />
		<osm-tag key="osmc_background" value="blue_circle" renderable="false" />
		<osm-tag key="osmc_background" value="blue_frame" renderable="false" />
		<osm-tag key="osmc_background" value="blue_round" renderable="false" />
		<osm-tag key="osmc_background" value="brown" renderable="false" />
		<osm-tag key="osmc_background" value="brown_circle" renderable="false" />
		<osm-tag key="osmc_background" value="brown_frame" renderable="false" />
		<osm-tag key="osmc_background" value="brown_round" renderable="false" />
		<osm-tag key="osmc_background" value="gray" renderable="false" />
		<osm-tag key="osmc_background" value="gray_circle" renderable="false" />
		<osm-tag key="osmc_background" value="gray_frame" renderable="false" />
		<osm-tag key="osmc_background" value="gray_round" renderable="false" />
		<osm-tag key="osmc_background" value="green" renderable="false" />
		<osm-tag key="osmc_background" value="green_circle" renderable="false" />
		<osm-tag key="osmc_background" value="green_frame" renderable="false" />
		<osm-tag key="osmc_background" value="green_round" renderable="false" />
		<osm-tag key="osmc_background" value="none" renderable="false" />
		<osm-tag key="osmc_background" value="orange" renderable="false" />
		<osm-tag key="osmc_background" value="orange_circle" renderable="false" />
		<osm-tag key="osmc_background" value="orange_frame" renderable="false" />
		<osm-tag key="osmc_background" value="orange_round" renderable="false" />
		<osm-tag key="osmc_background" value="purple" renderable="false" />
		<osm-tag key="osmc_background" value="purple_circle" renderable="false" />
		<osm-tag key="osmc_background" value="purple_frame" renderable="false" />
		<osm-tag key="osmc_background" value="purple_round" renderable="false" />
		<osm-tag key="osmc_background" value="red" renderable="false" />
		<osm-tag key="osmc_background" value="red_circle" renderable="false" />
		<osm-tag key="osmc_background" value="red_frame" renderable="false" />
		<osm-tag key="osmc_background" value="red_round" renderable="false" />
		<osm-tag key="osmc_background" value="white" renderable="false" />
		<osm-tag key="osmc_background" value="white_circle" renderable="false" />
		<osm-tag key="osmc_background" value="white_frame" renderable="false" />
		<osm-tag key="osmc_background" value="white_round" renderable="false" />
		<osm-tag key="osmc_background" value="yellow" renderable="false" />
		<osm-tag key="osmc_background" value="yellow_circle" renderable="false" />
		<osm-tag key="osmc_background" value="yellow_frame" renderable="false" />
		<osm-tag key="osmc_background" value="yellow_round" renderable="false" />
		<osm-tag key="osmc_foreground" value="ammonit" renderable="false" />
		<osm-tag key="osmc_foreground" value="backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_ammonit" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_crest" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_tower" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="black_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="blue_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="brown_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="green_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="heart" renderable="false" />
		<osm-tag key="osmc_foreground" value="hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="L" renderable="false" />
		<osm-tag key="osmc_foreground" value="mine" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="orange_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="purple_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_crest" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_tower" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_wheel" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="red_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="shell" renderable="false" />
		<osm-tag key="osmc_foreground" value="shell_modern" renderable="false" />
		<osm-tag key="osmc_foreground" value="tower" renderable="false" />
		<osm-tag key="osmc_foreground" value="triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_crest" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_shell" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_wheelchair" renderable="false" />
		<osm-tag key="osmc_foreground" value="white_x" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_arch" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_backslash" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_bar" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_bowl" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_circle" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_corner" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_cross" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_diamond" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_diamond_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_dot" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_fork" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_hexagon" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_hiker" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_L" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_lower" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_pointer" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_rectangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_rectangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_right" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_shell" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_shell_modern" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_slash" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_stripe" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_triangle" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_triangle_line" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_triangle_turned" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_turned_T" renderable="false" />
		<osm-tag key="osmc_foreground" value="yellow_x" renderable="false" />
